/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Iniciar un nuevo análisis (RF06, RF09, RF23) */
        post: operations["createAnalysis"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyses/{analysisId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysisId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Estados posibles de un análisis
         * @enum {string}
         */
        AnalysisStatus: "pending" | "running" | "completed" | "failed";
        /** @enum {string} */
        ProtectionType: "waf" | "proxy" | "captcha" | "rate_limiting";
        /** @description Formato de error único para toda la API (RFC 7807) */
        ProblemDetail: {
            type?: string;
            title: string;
            status: number;
            detail?: string;
        };
        /** @description Resumen de un análisis, tal como se ve en el historial (RF20) */
        Analysis: {
            /** Format: uuid */
            id: string;
            /** Format: uri */
            targetUrl: string;
            status: components["schemas"]["AnalysisStatus"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            finishedAt?: string | null;
        };
        /** @description Analysis + resultados completos (RF21, RF22) */
        AnalysisDetail: components["schemas"]["Analysis"] & {
            protections?: components["schemas"]["ProtectionFinding"][];
            vulnerabilities?: components["schemas"]["VulnerabilityFinding"][];
            /** @description Mensaje para RNF09-11 cuando status=failed */
            errorMessage?: string | null;
        };
        /** @description Detalle de una protección detectada */
        ProtectionFinding: {
            type: components["schemas"]["ProtectionType"];
            details?: string;
        };
        /** @description Detalle de una vulnerabilidad encontrada */
        VulnerabilityFinding: {
            type: string;
            /** @enum {string} */
            severity: "low" | "medium" | "high" | "critical";
            description: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createAnalysis: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uri */
                    targetUrl: string;
                };
            };
        };
        responses: {
            /** @description Análisis creado y encolado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Analysis"];
                };
            };
            /** @description Ya existe un análisis en curso (RN01, RN14) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description URL con formato inválido o bloqueada por la protección SSRF (RNF11) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
}
