# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-09-22T02:41:30+00:00

from __future__ import annotations

from enum import Enum
from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, Field


class AnalysisStatus(Enum):
    pending = 'pending'
    running = 'running'
    completed = 'completed'
    failed = 'failed'


class ProtectionType(Enum):
    waf = 'waf'
    proxy = 'proxy'
    captcha = 'captcha'
    rate_limiting = 'rate_limiting'


class ProblemDetail(BaseModel):
    type: str | None = None
    title: str
    status: int
    detail: str | None = None


class Analysis(BaseModel):
    id: UUID
    targetUrl: AnyUrl
    status: AnalysisStatus
    createdAt: AwareDatetime
    finishedAt: AwareDatetime | None = None


class ProtectionFinding(BaseModel):
    type: ProtectionType
    details: str | None = None


class Severity(Enum):
    low = 'low'
    medium = 'medium'
    high = 'high'
    critical = 'critical'


class VulnerabilityFinding(BaseModel):
    type: str
    severity: Severity
    description: str


class AnalysisDetail(Analysis):
    protections: list[ProtectionFinding] | None = None
    vulnerabilities: list[VulnerabilityFinding] | None = None
    errorMessage: str | None = Field(
        None, description='Mensaje para RNF09-11 cuando status=failed'
    )
